s = open(r'../Остальные данные/соп09.csv', 'r')
a = s.read()
b = a.replace(',','')
d = b.replace('.',',')
c = d.replace('[','')
e = c.replace(']','')
print(e)
sav = open(r'../Остальные данные/соп09Labv.txt', 'w')
sav.write(e)
sav.close()
s.close()